/**
 * Module integration catalog — every LIMS module exposes events, actions, and entity types
 * compatible with the workflow engine.
 */

import type { LimsModule, SystemEventType } from "./types.js";

export interface ModuleIntegration {
  module: LimsModule;
  label: string;
  description: string;
  entityTypes: string[];
  events: SystemEventType[];
  /** Action identifiers modules expose for workflow nodes / API calls */
  actions: string[];
}

export const MODULE_INTEGRATIONS: ModuleIntegration[] = [
  {
    module: "sample_lifecycle",
    label: "Sample Lifecycle",
    description: "Create, receive, assign, track, and complete samples",
    entityTypes: ["sample", "aliquot"],
    events: ["sample.created", "sample.received", "sample.assigned", "sample.completed"],
    actions: ["create_sample", "receive_sample", "assign_sample", "complete_sample", "hold_sample"],
  },
  {
    module: "chain_of_custody",
    label: "Chain of Custody",
    description: "Custody transfers and evidence trail",
    entityTypes: ["custody_record"],
    events: ["sample.received", "sample.assigned"],
    actions: ["transfer_custody", "verify_custody"],
  },
  {
    module: "barcode_qr",
    label: "Barcode & QR",
    description: "Label generation and scan events",
    entityTypes: ["barcode", "qr_code"],
    events: ["sample.created", "document.uploaded"],
    actions: ["generate_barcode", "generate_qr", "validate_scan"],
  },
  {
    module: "instrument_integration",
    label: "Instrument Integration",
    description: "Instrument commands and data import",
    entityTypes: ["instrument", "instrument_run"],
    events: ["instrument.data_imported", "test.started", "test.completed"],
    actions: ["send_instrument_command", "import_instrument_data", "poll_instrument"],
  },
  {
    module: "test_scheduling",
    label: "Test Scheduling",
    description: "Schedule and track analytical tests",
    entityTypes: ["test", "test_schedule"],
    events: ["test.started", "test.completed", "schedule.date_reached"],
    actions: ["schedule_test", "start_test", "cancel_test", "reschedule_test"],
  },
  {
    module: "results_entry",
    label: "Results Entry & Review",
    description: "Enter, validate, and approve results",
    entityTypes: ["result", "result_set"],
    events: ["result.entered", "result.approved"],
    actions: ["enter_result", "validate_result", "approve_result", "reject_result"],
  },
  {
    module: "scientific_calculations",
    label: "Scientific Calculations",
    description: "Formula and calculation engines",
    entityTypes: ["calculation"],
    events: ["result.entered"],
    actions: ["run_calculation", "recalculate"],
  },
  {
    module: "electronic_signatures",
    label: "Electronic Signatures",
    description: "21 CFR Part 11 e-signatures",
    entityTypes: ["signature"],
    events: ["result.approved", "document.uploaded"],
    actions: ["request_signature", "verify_signature"],
  },
  {
    module: "coa_generation",
    label: "Certificate of Analysis",
    description: "Generate and release CoAs",
    entityTypes: ["coa"],
    events: ["result.approved", "sample.completed"],
    actions: ["generate_coa", "release_coa", "void_coa"],
  },
  {
    module: "reporting",
    label: "Reporting",
    description: "Operational and regulatory reports",
    entityTypes: ["report"],
    events: ["schedule.date_reached", "sample.completed"],
    actions: ["generate_report", "schedule_report", "export_report"],
  },
  {
    module: "dashboards",
    label: "Dashboards",
    description: "KPI and operational dashboards",
    entityTypes: ["dashboard"],
    events: ["schedule.date_reached"],
    actions: ["refresh_dashboard", "publish_widget_alert"],
  },
  {
    module: "inventory",
    label: "Inventory Management",
    description: "Stock levels and reordering",
    entityTypes: ["inventory_item"],
    events: ["inventory.threshold_reached"],
    actions: ["adjust_stock", "create_reorder", "receive_stock"],
  },
  {
    module: "reagents",
    label: "Reagents",
    description: "Reagent lot tracking and expiry",
    entityTypes: ["reagent", "reagent_lot"],
    events: ["inventory.threshold_reached", "schedule.date_reached"],
    actions: ["quarantine_reagent", "release_reagent", "expire_reagent"],
  },
  {
    module: "standards",
    label: "Standards",
    description: "Reference standards management",
    entityTypes: ["standard", "standard_lot"],
    events: ["inventory.threshold_reached", "schedule.date_reached"],
    actions: ["qualify_standard", "retire_standard"],
  },
  {
    module: "equipment",
    label: "Equipment Management",
    description: "Instrument and equipment registry",
    entityTypes: ["equipment"],
    events: ["equipment.calibration_due"],
    actions: ["register_equipment", "retire_equipment", "set_status"],
  },
  {
    module: "calibration_maintenance",
    label: "Calibration & Maintenance",
    description: "Calibration schedules and PM",
    entityTypes: ["calibration", "maintenance_work_order"],
    events: ["equipment.calibration_due", "schedule.date_reached"],
    actions: ["schedule_calibration", "complete_calibration", "schedule_pm"],
  },
  {
    module: "stability_studies",
    label: "Stability Studies",
    description: "Stability protocols and pull schedules",
    entityTypes: ["stability_study", "stability_pull"],
    events: ["schedule.date_reached", "sample.created"],
    actions: ["create_study", "schedule_pull", "record_pull"],
  },
  {
    module: "workflow_automation",
    label: "Workflow Automation",
    description: "Meta-automation and scheduled workflows",
    entityTypes: ["workflow", "workflow_execution"],
    events: ["workflow.manual_trigger", "schedule.date_reached"],
    actions: ["start_workflow", "cancel_execution", "publish_workflow"],
  },
  {
    module: "customer_portal",
    label: "Customer Portal",
    description: "External customer submissions",
    entityTypes: ["portal_request"],
    events: ["customer.request_submitted"],
    actions: ["accept_request", "reject_request", "request_info"],
  },
  {
    module: "client_approvals",
    label: "Client Approvals",
    description: "Client-facing approval chains",
    entityTypes: ["client_approval"],
    events: ["customer.request_submitted", "result.approved"],
    actions: ["request_client_approval", "record_client_decision"],
  },
  {
    module: "billing",
    label: "Billing",
    description: "Invoicing and charges",
    entityTypes: ["invoice", "charge"],
    events: ["invoice.generated", "sample.completed"],
    actions: ["generate_invoice", "void_invoice", "apply_charge"],
  },
  {
    module: "notifications",
    label: "Notifications",
    description: "Email, SMS, and in-app alerts",
    entityTypes: ["notification"],
    events: ["api.event_received"],
    actions: ["send_email", "send_sms", "send_in_app"],
  },
  {
    module: "api_integrations",
    label: "API Integrations",
    description: "Inbound/outbound API and webhooks",
    entityTypes: ["integration_endpoint"],
    events: ["api.event_received"],
    actions: ["invoke_webhook", "sync_external", "transform_payload"],
  },
  {
    module: "ai_data_review",
    label: "AI-Assisted Data Review",
    description: "AI review and anomaly detection",
    entityTypes: ["ai_review"],
    events: ["result.entered", "instrument.data_imported"],
    actions: ["run_ai_review", "flag_anomaly"],
  },
  {
    module: "user_onboarding",
    label: "User Onboarding",
    description: "New user provisioning flows",
    entityTypes: ["user"],
    events: ["user.created"],
    actions: ["provision_user", "send_welcome", "assign_training"],
  },
  {
    module: "role_approvals",
    label: "Role Approval Workflows",
    description: "Role and privilege approvals",
    entityTypes: ["role_request"],
    events: ["user.created"],
    actions: ["request_role", "approve_role", "revoke_role"],
  },
  {
    module: "laboratory_onboarding",
    label: "Laboratory Onboarding",
    description: "New lab / tenant setup",
    entityTypes: ["laboratory"],
    events: ["user.created"],
    actions: ["setup_lab", "configure_methods", "import_master_data"],
  },
  {
    module: "multi_site",
    label: "Multi-Site Operations",
    description: "Cross-site transfers and coordination",
    entityTypes: ["site", "site_transfer"],
    events: ["sample.assigned", "sample.received"],
    actions: ["transfer_site", "accept_transfer"],
  },
  {
    module: "quality_events",
    label: "Quality Events",
    description: "Deviations and quality incidents",
    entityTypes: ["quality_event"],
    events: ["quality_event.opened"],
    actions: ["open_quality_event", "close_quality_event", "link_capa"],
  },
  {
    module: "capa",
    label: "CAPA Workflows",
    description: "Corrective and preventive actions",
    entityTypes: ["capa"],
    events: ["capa.initiated", "quality_event.opened"],
    actions: ["initiate_capa", "close_capa", "verify_effectiveness"],
  },
  {
    module: "non_conformance",
    label: "Non-Conformance Management",
    description: "NCR intake and disposition",
    entityTypes: ["non_conformance"],
    events: ["non_conformance.reported"],
    actions: ["report_ncr", "dispose_ncr", "link_investigation"],
  },
  {
    module: "document_control",
    label: "Document Control",
    description: "Controlled documents and SOPs",
    entityTypes: ["document", "sop"],
    events: ["document.uploaded"],
    actions: ["upload_document", "approve_document", "obsolete_document"],
  },
  {
    module: "training_records",
    label: "Training Records",
    description: "Training assignments and currency",
    entityTypes: ["training_record", "training_assignment"],
    events: ["training.due", "user.created"],
    actions: ["assign_training", "complete_training", "expire_training"],
  },
  {
    module: "change_control",
    label: "Change Control",
    description: "Controlled change requests",
    entityTypes: ["change_request"],
    events: ["change_control.submitted"],
    actions: ["submit_change", "approve_change", "implement_change"],
  },
  {
    module: "method_validation",
    label: "Method Validation",
    description: "Analytical method validation studies",
    entityTypes: ["method_validation"],
    events: ["test.completed", "change_control.submitted"],
    actions: ["start_validation", "approve_protocol", "close_validation"],
  },
  {
    module: "audit_preparation",
    label: "Audit Preparation",
    description: "Audit packs and evidence collection",
    entityTypes: ["audit", "audit_finding"],
    events: ["schedule.date_reached", "document.uploaded"],
    actions: ["create_audit_pack", "assign_finding", "close_finding"],
  },
  {
    module: "compliance_reviews",
    label: "Compliance Reviews",
    description: "Periodic compliance and regulatory reviews",
    entityTypes: ["compliance_review"],
    events: ["schedule.date_reached"],
    actions: ["start_review", "record_finding", "close_review"],
  },
];

export function getModuleIntegration(module: LimsModule): ModuleIntegration | undefined {
  return MODULE_INTEGRATIONS.find((m) => m.module === module);
}
